[package]
name = "deduplicator"
version = "0.1.0"
authors = ["anatoliy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbr = "1.0.4"
sha2 = "0.9.2"
clap = "2.33.3"
